NAME_DISPLAY_MAP = {
    "vt_symbol": "本地代码",
    "direction": "方向",
    "price": "价格",
    "volume": "数量",
    "time": "执行时间（秒）",
    "interval": "每轮间隔（秒）",
    "offset": "开平",
    "active": "算法状态",
    "traded": "成交数量",
    "order_volume": "每笔委托数量",
    "timer_count": "本轮读秒",
    "total_count": "累计读秒",
    "template_name": "算法模板",
    "display_volume": "挂出数量",
    "stop_price": "触发价格",
    "price_add": "委托超价",
    "step_price": "网格交易间距",
    "step_volume": "网格交易数量",
    "order_type": "委托类型",
    "active_vt_symbol": "主动腿",
    "passive_vt_symbol": "被动腿",
    "spread_up": "价差上限",
    "spread_down": "价差下限",
    "max_pos": "最大持仓",

    "start_time": "开始时间",
    "end_time": "结束时间",

    "min_volume": "最小委托量",
    "max_volume": "最大委托量",
    "volume_change": "委托量变化",

    "upper_price": "价格区间(上)",
    "lower_price": "价格区间(下)",
    "trigger_price": "触发基准价",
    "rise_percent": "上涨%",
    "fall_down": "回落卖出%",
    "fall_percent": "下跌%",
    "rise_up": "反弹买入%",
    "order_amount": "每笔委托金额",
    "max_position": "最大持仓",
    "min_position": "最小底仓",
    "multiple_order": "倍数委托",
    "deadline": "截止日期",
    "give_up_bias": "偏差控制%",
    "buy_offset": "买入委托价+",
    "sell_offset": "卖出委托价-",
}
